package act13;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author JuanLuis
 */
public class SwingAreasTexto extends javax.swing.JFrame {

    public SwingAreasTexto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30));
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEscribir = new javax.swing.JTextArea();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30));
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaMostrar = new javax.swing.JTextArea();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30));
        jPanel3 = new javax.swing.JPanel();
        btnSobrescribir = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        btnAppend = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        btnLeerFich = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actividad 6. Punto 5");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMinimumSize(new java.awt.Dimension(86, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(368, 20));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Nombre del fichero:");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel2.add(jLabel1);

        txtRuta.setMaximumSize(new java.awt.Dimension(400, 30));
        txtRuta.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel2.add(txtRuta);

        jPanel1.add(jPanel2);
        jPanel1.add(filler1);

        jPanel4.setMaximumSize(new java.awt.Dimension(450, 14));
        jPanel4.setPreferredSize(new java.awt.Dimension(425, 25));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Texto a escribir:");
        jLabel2.setAlignmentX(0.5F);
        jPanel4.add(jLabel2);

        jPanel1.add(jPanel4);
        jPanel1.add(filler5);

        txtAreaEscribir.setColumns(20);
        txtAreaEscribir.setRows(5);
        jScrollPane1.setViewportView(txtAreaEscribir);

        jPanel1.add(jScrollPane1);
        jPanel1.add(filler2);

        jPanel5.setMaximumSize(new java.awt.Dimension(450, 14));
        jPanel5.setPreferredSize(new java.awt.Dimension(425, 25));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Contenido del fichero:");
        jLabel3.setAlignmentX(0.5F);
        jPanel5.add(jLabel3);

        jPanel1.add(jPanel5);
        jPanel1.add(filler6);

        txtAreaMostrar.setColumns(20);
        txtAreaMostrar.setRows(5);
        jScrollPane2.setViewportView(txtAreaMostrar);

        jPanel1.add(jScrollPane2);
        jPanel1.add(filler7);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        btnSobrescribir.setText("Sobrescribir");
        btnSobrescribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobrescribirActionPerformed(evt);
            }
        });
        jPanel3.add(btnSobrescribir);
        jPanel3.add(filler3);

        btnAppend.setText("Añadir al final");
        btnAppend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppendActionPerformed(evt);
            }
        });
        jPanel3.add(btnAppend);
        jPanel3.add(filler4);

        btnLeerFich.setText("Mostrar contenido");
        btnLeerFich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerFichActionPerformed(evt);
            }
        });
        jPanel3.add(btnLeerFich);

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSobrescribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobrescribirActionPerformed
        String nombre_fichero = txtRuta.getText();

        if (!nombre_fichero.equals("")) {
            File ruta = new File("src/act13/", nombre_fichero);
            FileWriter flujoSalida = null;

            String contenido = txtAreaEscribir.getText();
            try {
                flujoSalida = new FileWriter(ruta);
                flujoSalida.write(contenido);

            } catch (IOException ex) {
                System.out.println("IOException generada" + ex.getMessage());
            } finally {
                try {
                    if (flujoSalida != null) { flujoSalida.close();};
                } catch (IOException ex) {

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes introducir un nombre de fichero.");
        }

    }//GEN-LAST:event_btnSobrescribirActionPerformed

    private void btnAppendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppendActionPerformed
        String nombre_fichero = txtRuta.getText();

        if (!nombre_fichero.equals("")) {
            File ruta = new File("src/act13/", nombre_fichero);
            FileWriter flujoSalida = null;

            String contenido = "\n" + txtAreaEscribir.getText();
            try {
                flujoSalida = new FileWriter(ruta, true);
                flujoSalida.write(contenido);

            } catch (IOException ex) {
                System.out.println("IOException generada" + ex.getMessage());
            } finally {
                try {
                    if (flujoSalida != null) { flujoSalida.close();};
                } catch (IOException ex) {

                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes introducir un nombre de fichero.");
        }
    }//GEN-LAST:event_btnAppendActionPerformed

    private void btnLeerFichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerFichActionPerformed
        String nombre_fichero = txtRuta.getText();

        if (!nombre_fichero.equals("")) {
            File ruta = new File("src/act13/", nombre_fichero);
            FileReader flujoEntrada = null;

            String contenido = "";
            
            try {
                flujoEntrada = new FileReader(ruta);
                int c;
                while ((c = flujoEntrada.read()) != -1) {
                    contenido += (char)c;
                }

            } catch (IOException ex) {
                System.out.println("IOException generada" + ex.getMessage());
            } finally {
                try {
                    if (flujoEntrada != null) { flujoEntrada.close();};
                } catch (IOException ex) {

                }
            }

            txtAreaMostrar.setText(contenido);
        } else {
            JOptionPane.showMessageDialog(null, "Debes introducir un nombre de fichero.");
        }
    }//GEN-LAST:event_btnLeerFichActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SwingAreasTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SwingAreasTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SwingAreasTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SwingAreasTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingAreasTexto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppend;
    private javax.swing.JButton btnLeerFich;
    private javax.swing.JButton btnSobrescribir;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaEscribir;
    private javax.swing.JTextArea txtAreaMostrar;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}


/*

SABER SI UNA LETRA ES MAYÚSCULA
char letra = teclado.nextLine().charAt(0);
     if(Character.isUpperCase(letra)){         
          System.out.println("Mayuscula");             
}else{                  
          System.out.println("Minuscula");   
}

CAMBIAR LETRA DE MAYÚSCULA A MINÚSCULA Y VICEVERSA
char char1UpperCase = Character.toUpperCase(char1);
char char2LowerCase = Character.toLowerCase(char2);

 */
